# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13c609fb4ad38f0a8bda3fa9f43c83f07599aa923eb27a9a9d32b843643fd1bf9094eaffa421398192111a740c4f6e04aaf557ea08248fdfa47ad850f628be6c

test:
  secret_key_base: a9814cb8ae4d464c9dad65c010e6c3fe275a17e9d44fd9cd265b40ac4ffb30a56764336602fa5ac252b3ab5ca0244a0ce9daf8a91295086618c77d24df35bb52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
